# Generated by Django 4.2.7 on 2023-12-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='house_unit_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
