# Generated by Django 5.0.2 on 2024-02-11 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_alter_useraddress_house_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='house_unit_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='post_code',
            field=models.IntegerField(),
        ),
    ]
