# Generated by Django 5.0.2 on 2024-02-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_alter_useraddress_house_unit_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='house_unit_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
