# Generated by Django 4.2.10 on 2024-02-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_alter_useraddress_house_unit_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='additional_photos',
            field=models.ManyToManyField(blank=True, to='index.additionalphotos'),
        ),
    ]
