# Generated by Django 4.2.10 on 2024-02-18 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_additionalphotos_product_additional_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='additional_photos',
        ),
        migrations.AddField(
            model_name='product',
            name='additional_photos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.additionalphotos'),
        ),
    ]
