# Generated by Django 4.2.10 on 2024-02-18 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_remove_product_additional_photos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='additional_photos',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.additionalphotos'),
        ),
    ]
