# Generated by Django 4.2.10 on 2024-02-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_alter_product_additional_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='additional_photos',
        ),
        migrations.AddField(
            model_name='product',
            name='additional_photos',
            field=models.ManyToManyField(blank=True, to='index.additionalphotos'),
        ),
    ]
