# Generated by Django 4.2.10 on 2024-02-18 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_additionalphoto_delete_additionalphotos_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdditionalPhoto',
            new_name='AdditionalPhotos',
        ),
    ]
