# Generated by Django 4.2.10 on 2024-02-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0016_remove_product_additional_photos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='additional_photos',
            field=models.ImageField(blank=True, null=True, upload_to='media/additional_photos'),
        ),
        migrations.DeleteModel(
            name='AdditionalPhotos',
        ),
    ]
