# Generated by Django 4.2.10 on 2024-02-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0017_alter_product_additional_photos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='additional_photos',
            field=models.FileField(blank=True, null=True, upload_to='media/additional_photos'),
        ),
    ]
