# Generated by Django 5.0 on 2024-02-18 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0018_alter_product_additional_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='additional_photos',
            field=models.ImageField(blank=True, null=True, upload_to='media/additional_photos'),
        ),
    ]
