# Generated by Django 5.0 on 2024-02-19 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0019_alter_product_additional_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='additional_photos',
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_photos', models.FileField(upload_to='media/additional_photos', verbose_name='Additional Photos')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='index.product', verbose_name='Product')),
            ],
        ),
    ]
